language: php
sudo: required
dist: trusty

php:
  - 7.1

services:
  - mysql-5.7

before_install:
  - mysql -e 'CREATE DATABASE homestead_test;'

before_script:
  - cp .env.testing .env
  - composer self-update
  - composer install --no-interaction
  - php artisan key:generate
  - php artisan migrate
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - ./vendor/laravel/dusk/bin/chromedriver-linux &
  - php artisan serve > /dev/null 2>&1 &

script:
  - vendor/bin/phpunit
  - php artisan dusk